version: '3'

services:
  one:
    container_name: 'one'
    image: karrybit/tracing_playground
    command: '/one'
    ports:
      - '3000:3000'
    environment:
      - RUST_LOG=INFO
      - JAEGER_SERVICE_NAME=one
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
      - RUN_ON=docker-compose
    depends_on:
      - jaeger
  two:
    container_name: 'two'
    image: karrybit/tracing_playground
    command: '/two'
    ports:
      - '4000:4000'
    environment:
      - RUST_LOG=INFO
      - JAEGER_SERVICE_NAME=two
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
      - RUN_ON=docker-compose
    depends_on:
      - jaeger
  three:
    container_name: 'three'
    image: karrybit/tracing_playground
    command: '/three'
    ports:
      - '5000:5000'
    environment:
      - RUST_LOG=INFO
      - JAEGER_SERVICE_NAME=three
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
      - RUN_ON=docker-compose
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '9411:9411'
      - '14250:14250'
      - '14268:14268'
      - '14269:14269'
      - '16686:16686'
