version: '3'

services:
  one:
    image: karrybit/tracing_playground
    command: '/one'
    ports:
      - '3000:3000'
    environment:
      - RUST_LOG=INFO
    container_name: 'one'
  two:
    image: karrybit/tracing_playground
    command: '/two'
    ports:
      - '4000:4000'
    environment:
      - RUST_LOG=INFO
    container_name: 'two'
  three:
    image: karrybit/tracing_playground
    command: '/three'
    ports:
      - '5000:5000'
    environment:
      - RUST_LOG=INFO
    container_name: 'three'
  jaeger:
    hostname: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
