[package]
name = "one"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.9"
axum = "0.4.5"
tokio = { version = "1.17.0", features = ["full"] }

opentelemetry = { version = "0.17.0", features = ["trace", "rt-tokio"] }
opentelemetry-http = "0.6.0"
opentelemetry-jaeger = "0.16.0"
tracing = "0.1.31"
tracing-opentelemetry = "0.17.1"
tracing-subscriber = { version="0.3.9", features = ["env-filter", "json"] }
