[package]
name = "three"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.17"
tower = "0.4.12"
tonic = "0.6.2"
prost = "0.9.0"
futures = "0.3.21"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }

opentelemetry = { version = "0.17.0", features = ["trace", "rt-tokio"] }
opentelemetry-jaeger = "0.16.0"
opentelemetry-http = "0.6.0"
tracing = "0.1.31"
tracing-opentelemetry = "0.17.1"
tracing-subscriber = { version="0.3.9", features = ["env-filter", "json"] }

[build-dependencies]
tonic-build = "0.6.2"
